<a href="https://colab.research.google.com/github/Tagoore19/PDS-Assignment2/blob/main/Assignment2Tag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import pandas as pd

# Load the dataset (upload it to Colab or mount Google Drive and use the path accordingly)
df = pd.read_csv("/content/used_cars.csv")  # Adjust the path if needed
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

In [81]:
# Check how many missing values each column has
missing_values = df.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64

# **Question A**

In [82]:
# Loop through each column to check for and handle missing values
for col in df.columns:
    missing_count = df[col].isnull().sum()

    # Proceed only if the column has missing values
    if missing_count > 0:
        if pd.api.types.is_numeric_dtype(df[col]):
            # For numeric columns, use the median to fill missing values
            median_val = df[col].median()
            df[col].fillna(median_val, inplace=True)
            print(f"Imputed {missing_count} missing values in numeric column '{col}' with median = {median_val}")
        else:
            # For categorical/text columns, use the most frequent value (mode)
            mode_val = df[col].mode()[0]
            df[col].fillna(mode_val, inplace=True)
            print(f"Imputed {missing_count} missing values in categorical column '{col}' with mode = '{mode_val}'")

# Display how many missing values remain after imputation
print("\n✅ Count of Missing Values After Imputation:")
print(df.isnull().sum())

Imputed 2 missing values in categorical column 'Mileage' with mode = '18.9 kmpl'
Imputed 36 missing values in categorical column 'Engine' with mode = '1197 CC'
Imputed 36 missing values in categorical column 'Power' with mode = '74 bhp'
Imputed 38 missing values in numeric column 'Seats' with median = 5.0
Imputed 5032 missing values in categorical column 'New_Price' with mode = '4.78 Lakh'

✅ Count of Missing Values After Imputation:
Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
Price                0
dtype: int64

<ipython-input-82-cdd84849ffb5>:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)
<ipython-input-82-cdd84849ffb5>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)

In [83]:
missing_values = df.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
Price                0
dtype: int64

**Justification** : We began by checking the dataset for any missing values to ensure data completeness. For numerical columns, we chose to fill in the gaps using the median since it’s less influenced by extreme values and better represents the center in skewed distributions. For categorical columns, we used the mode, or the most frequently occurring value, to maintain logical consistency without introducing unfamiliar categories.

This approach allowed us to preserve the structure and distribution of the original dataset without deleting any rows or columns. As a result, we were able to cleanly fill all missing values, making the data ready for further analysis or machine learning tasks.

# **Question B**

In [87]:
# Remove text units and retain numeric values
df['Mileage'] = df['Mileage'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)
df['Engine'] = df['Engine'].astype(str).str.extract(r'(\d+)').astype(float)
df['Power'] = df['Power'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

# Clean 'New_Price' and convert to numeric
df['New_Price'] = df['New_Price'].str.replace(' Lakh', '', regex=True)
df['New_Price'] = pd.to_numeric(df['New_Price'], errors='coerce')
print(df[['Mileage', 'Engine', 'Power', 'New_Price']].head())

   Mileage  Engine   Power  New_Price
0    19.67  1582.0  126.20        NaN
1    13.00  1199.0   88.70       8.61
2    20.77  1248.0   88.76        NaN
3    15.20  1968.0  140.80        NaN
4    23.08  1461.0   63.10        NaN

# **Question C**

In [88]:
# Clean up any leading/trailing spaces in column names
df.columns = [col.strip() for col in df.columns]

# Convert categorical features into binary columns using one-hot encoding
df = pd.get_dummies(data=df, columns=['Fuel_Type', 'Transmission'], drop_first=True)

# Display the top rows of the updated DataFrame
print("Preview of DataFrame after one-hot encoding:\n", df.head())

Preview of DataFrame after one-hot encoding:
    Unnamed: 0                              Name    Location  Year  \
0           1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015
1           2                      Honda Jazz V     Chennai  2011
2           3                 Maruti Ertiga VDI     Chennai  2012
3           4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013
4           6            Nissan Micra Diesel XV      Jaipur  2013

   Kilometers_Driven Owner_Type  Mileage  Engine   Power  Seats  New_Price  \
0              41000      First    19.67  1582.0  126.20    5.0        NaN
1              46000      First    13.00  1199.0   88.70    5.0       8.61
2              87000      First    20.77  1248.0   88.76    7.0        NaN
3              40670     Second    15.20  1968.0  140.80    5.0        NaN
4              86999      First    23.08  1461.0   63.10    5.0        NaN

   Price  Fuel_Type_Electric  Fuel_Type_Petrol  Transmission_Manual
0  12.50               False             False                 True
1   4.50               False              True                 True
2   6.00               False             False                 True
3  17.74               False             False                False
4   3.50               False             False                 True

# **Question D**

In [91]:
from datetime import datetime

# Calculate car age based on current year
current_year = datetime.now().year
df['Car_Age'] = current_year - df['Year']
print("Added 'Car_Age' column:\n", df[['Year', 'Car_Age']].head())

Added 'Car_Age' column:
    Year  Car_Age
0  2015       10
1  2011       14
2  2012       13
3  2013       12
4  2013       12

In [92]:
print(df.head())

   Unnamed: 0                              Name    Location  Year  \
0           1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015
1           2                      Honda Jazz V     Chennai  2011
2           3                 Maruti Ertiga VDI     Chennai  2012
3           4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013
4           6            Nissan Micra Diesel XV      Jaipur  2013

   Kilometers_Driven Owner_Type  Mileage  Engine   Power  Seats  New_Price  \
0              41000      First    19.67  1582.0  126.20    5.0        NaN
1              46000      First    13.00  1199.0   88.70    5.0       8.61
2              87000      First    20.77  1248.0   88.76    7.0        NaN
3              40670     Second    15.20  1968.0  140.80    5.0        NaN
4              86999      First    23.08  1461.0   63.10    5.0        NaN

   Price  Fuel_Type_Electric  Fuel_Type_Petrol  Transmission_Manual  Car_Age
0  12.50               False             False                 True       10
1   4.50               False              True                 True       14
2   6.00               False             False                 True       13
3  17.74               False             False                False       12
4   3.50               False             False                 True       12

# **Question E**

In [47]:
df_selected = df[['Name', 'Location', 'Kms_Driven', 'Price']] if 'Kms_Driven' in df.columns else df[['Name', 'Location', 'Kilometers_Driven', 'Price']]
df_selected.head()

                               Name    Location  Kilometers_Driven  Price
0  Hyundai Creta 1.6 CRDi SX Option        Pune              41000  12.50
1                      Honda Jazz V     Chennai              46000   4.50
2                 Maruti Ertiga VDI     Chennai              87000   6.00
3   Audi A4 New 2.0 TDI Multitronic  Coimbatore              40670  17.74
4            Nissan Micra Diesel XV      Jaipur              86999   3.50

In [48]:
df_filtered = df[(df['Location'] == 'Pune') & (df['Price'] > 5)]
df_filtered.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.2,5.0,4.78,12.5,False,False,True,10
6,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,First,20.54,1598.0,103.6,5.0,4.78,5.2,False,False,True,12
12,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Second,0.00,2179.0,115.0,5.0,4.78,17.5,False,False,False,13
36,38,Mercedes-Benz M-Class ML 350 CDI,Pune,2013,85000,First,11.74,2987.0,254.8,5.0,4.78,28.0,False,False,False,12
61,63,Mercedes-Benz New C-Class 200 CDI Classic,Pune,2011,65000,Second,15.80,2148.0,170.0,5.0,4.78,10.0,False,False,True,14

In [93]:
# Rename Kilometers_Driven to Kms_Driven for clarity
df.rename(columns={'Kilometers_Driven': 'Kms_Driven'}, inplace=True)

In [94]:
df_sorted = df.sort_values(by='Price', ascending=False)
df_sorted[['Name', 'Price']].head()

                                             Name   Price
3952  Land Rover Range Rover 3.0 Diesel LWB Vogue  160.00
5620                   Lamborghini Gallardo Coupe  120.00
5752                       Jaguar F Type 5.0 V8 S  100.00
1457              Land Rover Range Rover Sport SE   97.07
1917                           BMW 7 Series 740Li   93.67

In [95]:
group_summary = df.groupby('Owner_Type')['Price'].mean().reset_index()
group_summary

       Owner_Type      Price
0           First  10.105076
1  Fourth & Above   3.415000
2          Second   7.839719
3           Third   5.348058